---
title: "Seminar2b_Ninadh"
author: "Ninadh"
date: "1/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(tibble)
```

looking at mpg data frame

```{r}
ggplot2::mpg
```

point graph to create a graph with displ on the x-axis and hwy on the y-axis:

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
	geom_line(aes(x=displ, y=hwy))
```

the plot wiht the line displays a negative corelation of displ with hwy.

```{r} 
# to have the car class in different colors
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
```

```{r}
# the class in differnet size
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class))
```


```{r}
#better still, i can layer it up
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class)) +
	geom_smooth(aes(displ, hwy))
```

```{r}
# just wanted to have fun with the color gradient in year
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = year)) +
	geom_smooth(aes(displ, hwy))

```







